---
kind: pipeline
type: docker
name: linux-build

steps:
  - name: build_amd64
    image: golang:1.15-alpine
    commands:
      - sh scripts/build.sh
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: build_arm64
    image: golang:1.15-alpine
    commands:
      - sh scripts/build.sh
    environment:
      GOARCH: arm64
      GOOS: linux

  - name: build_arm
    image: golang:1.15-alpine
    commands:
      - sh scripts/build.sh
    environment:
      GOARCH: arm
      GOOS: linux

  - name: publish_amd64
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.amd64
      repo: alinbalutoiu/dynamicdns-go
      tags: linux-amd64-${DRONE_BRANCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish_arm64
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.arm64
      repo: alinbalutoiu/dynamicdns-go
      tags: linux-arm64-${DRONE_BRANCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish_arm
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.arm
      repo: alinbalutoiu/dynamicdns-go
      tags: linux-arm-${DRONE_BRANCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: manifest

steps:
  - name: publish
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: alinbalutoiu/dynamicdns-go:latest
      template: alinbalutoiu/dynamicdns-go:OS-ARCH-${DRONE_BRANCH}
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64

depends_on:
  - linux-arm64
  - linux-arm
  - linux-amd64
